name: portfolio-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyter
  - pip
  - pip:
      - optuna
      - streamlit
